version: '3.9'

services:
  bot:
    image: nikuma0/artsbot:latest
    volumes:
      - db:/home/app/web/sqlite
    env_file:
      - .env
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  db:
