version: '3.9'

services:
  bot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - db:/home/app/web/sqlite
    env_file:
      - .env

volumes:
  db:

